const PEOPLE_TYPES = {
    UNKNOWN: 'UNKNOWN',
    DEVEDOR: 'DEVEDOR',
    ADMINISTRADOR_INSOLVENCIA: 'ADMINISTRADOR_INSOLVENCIA',
    CREDOR: 'CREDOR',
    INSOLVENTE: 'INSOLVENTE'
};

module.exports = {
    PEOPLE_TYPES
};