const PEOPLE_TYPES = {
    UNKNOWN: 'UNKNOWN',
    DEVEDOR: 'DEVEDOR',
    ADMINISTRADOR_INSOLVENCIA: 'ADMINISTRADOR_INSOLVENCIA',
    CREDOR: 'CREDOR',
    INSOLVENTE: 'INSOLVENTE'
};

const DB_PEOPLE_TYPE_IDS = {
    ADMINISTRADOR_INSOLVENCIA: 1,
    INSOLVENTE: 2,
    CREDOR: 3,
    DEVEDOR: 4,
    UNKNOWN: 5
};

module.exports = {
    PEOPLE_TYPES,
    DB_PEOPLE_TYPE_IDS
};